# .checkov.yaml
directory:
  - .

# Only check Terraform files
framework:
  - terraform

# Be strict; make the CI pipeline fail if vulnerabilities are found
soft-fail: false

# Skip checks that are not applicable to your specific architectural decisions
# Uncomment lines below if you need to bypass specific checks
# skip-check:
#   - CKV_AWS_111 # Example: IAM Policy allows '*'. 

# Ensure output is clean for CI/CD logs
quiet: true

# Optional: Output in JUnit XML format for better CI/CD reporting
output: cli