name: "Terraform Production Release"

on:
  push:
    tags:
      - 'v*' # Trigger only on version tags (e.g., v1.0.0)

jobs:
  validate-and-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: environments/prod # Targeting your prod env
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: TFLint
        run: |
          curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash
          tflint --init
          tflint --recursive ../../

      - name: tfsec
        uses: aquasecurity/tfsec-action@v1.0.3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -no-color -out=tfplan
        env:
          TF_VAR_license_key: ${{ secrets.TABLEAU_LICENSE }}
          TF_VAR_db_password: ${{ secrets.DB_PASSWORD }}

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1
          TF_VAR_license_key: ${{ secrets.TABLEAU_LICENSE }}
          TF_VAR_db_password: ${{ secrets.DB_PASSWORD }}